# Install the collector watchdog into the current user's Startup folder.
# Requires no elevation. Undo with uninstall-watchdog.ps1.
#
# The launcher is generated here rather than shipped, so the repository carries
# no absolute path belonging to whoever happened to build it.

$ErrorActionPreference = "Stop"

$Root    = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$Startup = [Environment]::GetFolderPath("Startup")
$Dst     = Join-Path $Startup "palimpsest-watchdog.cmd"
$Guard   = Join-Path $Root "scripts\watchdog.ps1"

if (-not (Test-Path $Guard)) { throw "watchdog.ps1 not found at $Guard" }

@"
@echo off
REM Generated by scripts\install-watchdog.ps1 -- do not edit by hand.
REM Re-checks the Palimpsest collector every 15 minutes for the life of the session.
start "" /min powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -Command ^
 "while (`$true) { try { & '$Guard' } catch {}; Start-Sleep -Seconds 900 }"
"@ | Set-Content -Path $Dst -Encoding ascii

Write-Output "installed -> $Dst"
Write-Output "watching   -> $Root"

# Start now rather than waiting for the next logon.
& $Guard
Write-Output "watchdog run once; collector should be up"
